version: "3.9" 
services: 
    serviceMath: 
        ports: 
            - "8081:8080" 
        image: "math:latest" 
    serviceStats: 
        ports: 
            - "8082:8080" 
        image: "stats:latest" 
    gateway: 
        ports: 
            - "8080:8080" 
        image: "gateway:latest"